module.exports = {
  CREATE_GROUP_TABLE: `CREATE TABLE IF NOT EXISTS GROUPS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name Varchar(20) NOT NULL
)`,

  CREATE_USER_TABLE: `CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name Varchar(20) NOT NULL, 
    gmail Varchar(50) NOT NULL UNIQUE,
    password Varchar(50) NOT NULL
)`,
  CREATE_GROUP_MEMBERS: `CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    group_id INT NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (member_id) REFERENCES USERS(id)
)`,
  CREATE_PRIVATE_CHAT_TABLE: `CREATE TABLE IF NOT EXISTS PRIVATE_CHATS(
       id INT AUTO_INCREMENT PRIMARY KEY,
       message Varchar(1000) NOT NULL,
       sender_id INT NOT NULL,
       receiver_id INT,
       FOREIGN KEY (sender_id) REFERENCES USERS(id),
       FOREIGN KEY (receiver_id) REFERENCES USERS(id)
)`,
  CREATE_GROUP_CHAT_TABLE: `CREATE TABLE IF NOT EXISTS GROUP_CHATS(
  id INT AUTO_INCREMENT PRIMARY KEY,
  message Varchar(1000) NOT NULL,
  sender_id INT NOT NULL,
  group_id INT NOT NULL,
  FOREIGN KEY (sender_id) REFERENCES USERS(id),
  FOREIGN KEY (group_id) REFERENCES GROUPS(id)
)`,
  CREATE_PRIVATE_RECENT_TABLE:`CREATE TABLE IF NOT EXISTS RECENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    person1 INT NOT NULL,
    person2 INT NOT NULL,
    time TIMESTAMP,
    FOREIGN KEY (person1) REFERENCES USERS(id),
    FOREIGN KEY (person2) REFERENCES USERS(id),
    CHECK(person1<person2)
  )`,
  CREATE_GROUP_RECENT_TABLE:`CREATE TABLE IF NOT EXISTS GROUP_RECENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    Grp INT NOT NULL,
    Person INT NOT NULL,
    time TIMESTAMP,
    FOREIGN KEY (Grp) REFERENCES GROUPS(id),
    FOREIGN KEY (Person) REFERENCES USERS(id)
  )`
};
