const ACTION_TYPES = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  INITIALISE_CHAT: "INITIALISE_CHAT",
  ADD_SINGLE_CHAT: "ADD_SINGLE_CHAT",
  ADD_TOKEN: "ADD_TOKEN",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  ADD_RECENTS: "ADD_RECENTS",
  CLEAR_CHAT: "CLEAR_CHAT",
  SEARCH_RESULTS: "SEARCH_RESULTS",
  UPDATE_RECENTS: "UPDATE_RECENTS",
};

export default ACTION_TYPES;
