const ACTION_TYPES ={ 
    LOGIN_USER : "LOGIN_USER",
    LOGOUT_USER : "LOGOUT_USER",
    INITIALISE_CHAT:"INITIALISE_CHAT",
    ADD_SINGLE_CHAT : "ADD_SINGLE_CHAT",
    ADD_TOKEN:"ADD_TOKEN",
    ERROR:"ERROR",
    SUCCESS:"SUCCESS"
}

export default ACTION_TYPES;